default: &default
  adapter: mysql2
  encoding: utf8
  pool: 16
  port: 3306
  username: <%= Rails.application.secrets.database[:username] %>
  password: <%= Rails.application.secrets.database[:password] %>

development:
  <<: *default
  database: library-development

test:
  <<: *default
  database: library-production

production:
  <<: *default
  database: library-production